controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

    panda_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

panda_arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

panda_hand_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2